# Generated by Django 4.0.5 on 2022-07-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=45)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.TextField(blank=True, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('state_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Publicevent',
            fields=[
                ('public_event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.address')),
            ],
            options={
                'db_table': 'PublicEvent',
            },
        ),
    ]
