# Generated by Django 4.0.5 on 2022-07-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_citysuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysuggestion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
