# Generated by Django 4.0.5 on 2022-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_desc', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
