# Generated by Django 4.0.6 on 2022-07-26 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, default=None, max_length=64)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('group_desc', models.TextField(blank=True, default=None, max_length=512, null=True)),
                ('banner', models.ImageField(blank=True, default='default.jpeg', upload_to='group_banner')),
                ('group_admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, default=None, upload_to='publicevents_banner')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEvent',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=128)),
                ('post_content', models.TextField(blank=True, max_length=256, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupPost',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('member_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group_id', 'member_id')},
            },
        ),
        migrations.CreateModel(
            name='groupPostComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupPost_Comment',
            },
        ),
        migrations.CreateModel(
            name='groupEventComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupevent')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEvent_Comment',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.groupevent')),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('rsvp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEventRSVP',
                'unique_together': {('group_id', 'rsvp_id', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='Groupadmin',
            fields=[
                ('group_admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.member')),
            ],
            options={
                'db_table': 'GroupAdmin',
                'unique_together': {('group_admin_id', 'group_user')},
            },
        ),
    ]
