# Generated by Django 4.0.6 on 2022-07-17 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, default=None, max_length=64)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('group_desc', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('group_admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('member_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Groupuser',
            fields=[
                ('group_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupUser',
                'unique_together': {('group_user_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Groupadmin',
            fields=[
                ('group_admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupuser')),
            ],
            options={
                'db_table': 'GroupAdmin',
                'unique_together': {('group_admin_id', 'group_user')},
            },
        ),
    ]
