# Generated by Django 4.0.5 on 2022-07-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='groupID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
