# Generated by Django 4.0.5 on 2022-07-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_member_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='isAdmin',
        ),
    ]
