# Generated by Django 4.0.5 on 2022-07-16 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_remove_member_isadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupAdminID',
            new_name='group_admin',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupDesc',
            new_name='group_desc',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupID',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupName',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='groupID',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='joinDate',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='memberID',
            new_name='member_id',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('group_id', 'member_id')},
        ),
        migrations.CreateModel(
            name='Groupuser',
            fields=[
                ('group_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupUser',
                'unique_together': {('group_user_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Groupadmin',
            fields=[
                ('group_admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupuser')),
            ],
            options={
                'db_table': 'GroupAdmin',
                'unique_together': {('group_admin_id', 'group_user')},
            },
        ),
    ]
