# Generated by Django 4.0.5 on 2022-07-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NON_BINARY', 'Non-Binary')], max_length=10)),
                ('dob', models.DateField(max_length=11)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=45)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generalUser',
            fields=[
                ('trackingID', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'generalUser',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profileDesc', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='uploads')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
