# Generated by Django 4.0.6 on 2022-07-16 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profileDesc', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='uploads')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Supportstaff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'SupportStaff',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='generaluser',
            table='generalUser',
        ),
        migrations.CreateModel(
            name='Requestsupport',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=52)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('REP', 'Report User or Content'), ('ONB', 'Registration Issues'), ('BUG', 'PlayDate Not Working'), ('OTH', 'Other')], default='ONB', max_length=3)),
                ('details', models.TextField(max_length=500)),
                ('accountID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.generaluser')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.supportstaff')),
            ],
            options={
                'db_table': 'RequestSupport',
            },
        ),
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FriendList',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('dependent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('dob', models.DateTimeField()),
                ('interests', models.CharField(max_length=45)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.profile')),
            ],
            options={
                'db_table': 'Dependent',
            },
        ),
        migrations.CreateModel(
            name='Backendadmin',
            fields=[
                ('backend_admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BackendAdmin',
                'unique_together': {('backend_admin_id', 'user')},
            },
        ),
    ]
